### ISSUE TITLE
Macos appearance colors not found in tkinter.

### ISSUE THREAD

**Issue by Saadmairaj** [Saadmairaj/tkmacosx#20]
**Describe the bug**
The appearance colors like `"systemWindowBackgroundColor"` and `"systemTextColor"` are giving error `_tkinter.TclError: unknown color name` for some macOS for some people but on my machine they work perfectly fine. 

**To Reproduce**
```
import tkinter as tk
from tkmacosx import Button

window = tk.Tk()
button = Button(window, text='Text')#, highlightbackground='gray15', fg='pink')
button.pack()
window.mainloop()
```

**Expected behavior**
```
File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 2569, in __init__
    self.tk.call(
_tkinter.TclError: unknown color name "systemWindowBackgroundColor"
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 11.2.3
 - tkmacosx v1.0.1 _(yanked on pypi)_

**Comment by rgerrits** [comment]
fwiw, I also encountered the this issue without tkmacosx, but when trying to use the MacOS system colors on a regular tk.Button.

BigSur 11.3.1 + Python 3.9.5

If I install Python via the macOS 64-bit Intel installer, then I have this issue.
If I install Python via the macOS 64-bit universal2 installer, then everything works oke.
