### ISSUE TITLE
Buttons becoming transparent when window is not selected

### ISSUE THREAD

**Issue by vic025** [Saadmairaj/tkmacosx#21]
Hey

I was wondering if this was a bug, or if I'm just missing something. When the window is in focus, the buttons look fine, however, when I click outside of the window / the window is no longer in focus, the buttons go transparent.

In focus:
<img width="156" alt="In focus" src="https://user-images.githubusercontent.com/83489702/117761019-c1140100-b27a-11eb-84f7-25e95a7d98fa.png">

Out of focus:
<img width="151" alt="Out of focus" src="https://user-images.githubusercontent.com/83489702/117761026-c2452e00-b27a-11eb-9aec-1d68ebefc553.png">

Thanks

**Comment by Saadmairaj** [comment]
Circumvent? I didn't get it. Please elaborate. But if u mean to set a specific colour then just set borderless to False and use highlightbackground option.

example:
```python
Button(root, text="Hello", borderless=False, highlightbackground="pink")
```

_By default borderless is false but in future updates, I'll set it true by deafult._

**Comment by Saadmairaj** [comment]
Yes, it will not work if borderless is set to True. It is because the purpose of borderless is to blend the highlightbackground with the parent's background colour and change the highlightbackground of the button automatically when the bg of the parent widget is changed.

**Comment by vic025** [comment]
I see. Thanks for the insight. Initially I asked this question because I had colourful buttons, and therefore, 

Before (in focus)
<img width="158" alt="Screen Shot 2021-05-13 at 9 18 48 AM" src="https://user-images.githubusercontent.com/83489702/118045755-74403f80-b3cc-11eb-8ea0-09a81b4b4458.png">

After (out of focus)
<img width="156" alt="Screen Shot 2021-05-13 at 9 18 55 AM" src="https://user-images.githubusercontent.com/83489702/118045780-7c987a80-b3cc-11eb-8899-8a2da456e871.png">

Ill try do the colourful buttons a different way then. Thanks again!
