### ISSUE TITLE
Simple colorscale is producing errors

### ISSUE THREAD

**Issue by RPS1222** [Saadmairaj/tkmacosx#29]
The code I'm using is basically copied from the reference guide, and it's producing tons of errors whenever I move the slider. The code is after the error

`Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/Users/username/Library/Python/3.8/lib/python/site-packages/tkmacosx/basewidgets/colorscale_base.py", line 243, in _check_marker
    return self._move_marker(evt)
  File "/Users/username/Library/Python/3.8/lib/python/site-packages/tkmacosx/basewidgets/colorscale_base.py", line 217, in _move_marker
    self._create_items('create', safe_create=True, avoid=('gradient', 'borderline'),
  File "/Users/username/Library/Python/3.8/lib/python/site-packages/tkmacosx/basewidgets/colorscale_base.py", line 156, in _create_items
    ids.append(self._rounded(markerbg_points, **cnf))
  File "/Users/username/Library/Python/3.8/lib/python/site-packages/tkmacosx/utils/__init__.py", line 306, in _rounded
    x1, y1, x2, y2, c = _agsmerge((ags, args))
ValueError: not enough values to unpack (expected 5, got 0)`

```py
import tkinter as tk
from tkinter import Variable, colorchooser
from tkmacosx import Button, Colorscale, ColorVar

tkWindow = tk.Tk()
tkWindow.geometry('400x150')
tkWindow.title("cnjnckanckan")

bgvar = ColorVar(value="white")

b1 = Button(tkWindow, text = "baba", bg=bgvar,fg="blue", borderless=1)
b1.pack()

Colorscale(tkWindow, value="hex", variable=bgvar, mousewheel=1).pack()

tkWindow.mainloop()

**Comment by Saadmairaj** [comment]
Hi @RPS1222
I need some more details to further investigate this issue. The above code snippet works perfectly fine in my environment with no errors.

My env:
python:  3.8.3 with anaconda
tkmacosx: 1.0.3
Tcl/Tk: 8.6.10

A possible cause for this issue could be the difference in the version of Tcl/Tk that your python is bundled with. You can check your Tcl/Tk version with the following code

```python
import tkinter
print(tkinter.Tcl().call("info", "patchlevel"))
```

If the version of Tcl/Tk < 8.6.8 then please try to update it, if you find difficulties in updating it then I'll recommend using [anaconda](https://docs.anaconda.com/anaconda/install/mac-os/)

**Comment by RPS1222** [comment]
Using that returns 8.6.11 on Python version 3.9.7 and tkmacosx 1.0.3. Originally, I was using an older version of tkinter, but I updated it and still get the same errors.

**Comment by Saadmairaj** [comment]
Unfortunately, I'm not able to replicate this issue. On my system, everything is working without any errors. Can you please try to install python with conda and then try to run with it?
