### ISSUE TITLE
Collision with ttkthemes

### ISSUE THREAD

**Issue by tcarroll2** [Saadmairaj/tkmacosx#3]
When trying to use tkmacosx (tkm) it appears it is colliding with ttkthemes (tkt).

I'm getting errors when using a tkm.Button. I get a parameter issue when I destroy a TopLevel window.  Anyone else having this problem?

**Comment by Saadmairaj** [comment]
Can you post the traceback error?

**Comment by tcarroll2** [comment]
Sorry, but I've moved on from this package.

**Comment by Saadmairaj** [comment]
The issue was not because of ttkthemes, the issue was related to the parent window being destroyed by the tkmacosx button which is now fixed in tkmacosx 0.1.3.
