### ISSUE TITLE
Some major bugs I noticed while using tkmacosx buttons!

### ISSUE THREAD

**Issue by Akascape** [Saadmairaj/tkmacosx#39]
I noticed some bugs while using tkmacosx buttons in mac.

1) When we change the tkinter window or put the window in the background, the buttons (bg colors) disappear. But it appears again only after selecting the window.

2) When we change the button 'state' to DISABLED, it makes the whole button color to black.
Instead it should have a slight grey transparent layout.

3) Major bug:
After placing the button, when we change the text of button by button.configure, then the button increases in size and the text is also displaced upward (this happens if width or height parameters were given in the main button code) 
(Please try to fix it)

4) When we select the button, the focus layout around it do not change immediately even after releasing the mouse. Any extra parameter should be added to fix it.

(I am using python 3.10)

**Comment by Saadmairaj** [comment]
Hi Akascape, thanks for reporting these bugs.
Will try to fix them with the next release

**Comment by Akascape** [comment]
Thanks for your response, I hope you will fix these bugs (specially bug #1 and #3).
I am building a big project with this module so I hope that this module will get updated soon. 😁

**Comment by Akascape** [comment]
> Hi Akascape, thanks for reporting these bugs.
> Will try to fix them with the next release

Thanks for your response, I hope you will fix these bugs (specially bug #1 and #3).
I am building a big project with this module so I hope that this module will get updated soon. 😁

**Comment by Saadmairaj** [comment]
Hi, I've checked and fixed points 1 and 2 in tkmacosx-1.0.5 , however 

1. We can set `disabledforground` and `disbaledbackground` colors
  ![point1](https://user-images.githubusercontent.com/46227224/170785385-484ff140-2e84-4f57-a3d5-194988f039ec.gif)

2. Till now this was an intended behaviour but this has been changed to look better
3. I tried to replicate it on my system but it works just fine no matter how I change the text of the button, maybe you can share more details on your case
![point3](https://user-images.githubusercontent.com/46227224/170785405-715b856a-cc55-427d-84ca-bbabcc09ec21.gif)

4. it works fine as well, maybe share some button configures or gif

**Comment by Akascape** [comment]
I don't know but there were some issues in my mac, moreover I have not upgraded my mac from a very long time.
But I have somewhat fixed those bugs using other methods. 
Btw thanks a lot for your response.

**Comment by SidyKing** [comment]
my popup button disappeared  while using tkmacosx
