### ISSUE TITLE
Import Error: Unable to import 'tkmacosx'

### ISSUE THREAD

**Issue by vendz** [Saadmairaj/tkmacosx#9]
I install tkmacosx on my mac by: 
```sh
pip install tkmacosx
```
but when I use👇🏻. i get an error
```sh
from tkinter import *
from tkmacosx import Button
```

ERROR: ```Unable to import 'tkmacosx'pylint(import-error)```

**Comment by Saadmairaj** [comment]
As far I can see from the error message it doesn't has to do with the package tkmacosx itself. You have not installed pylint in the same environment that contains your python packages. Please check stackoverflow about the pylint error.

**Comment by vendz** [comment]
I have installed pylint in the same environment that contains python packages.
